### ISSUE TITLE
Bug: Incorrect import statement in documentation for dropDatabase function

### ISSUE THREAD

**Issue by IbrahimBagalwa** [tada5hi/typeorm-extension#1056]
### Versions
- Browser: Arc 1.52.0
- OS: macOS Sonoma 14.5

### Reproduction
The documentation contains an error in the code example for [dropping a database](https://typeorm-extension.tada5hi.net/guide/database-api-reference.html#dropDatabase). The example code omits the import statement for the `dropDatabase` function and imports the `createDatabase` instead.

### Steps to reproduce
1. Visit the [documentation page](https://typeorm-extension.tada5hi.net/guide/database-api-reference.html#dropDatabase) where the code example is provided.
2. Check the import statement in the code snippet example (`Example: Simple`).
3.   Encounter an error due to the missing import.

### What is Expected?

The `dropDatabase` function should be imported.
```typescript
import { dropDatabase } from 'typeorm-extension';

(async () => {
    await dropDatabase();
})();
```

### What is actually happening?
```typescript
import { createDatabase } from 'typeorm-extension';

(async () => {
    await dropDatabase();
})();
```

**Comment by tada5hi** [comment]
good catch!
Thanks
