### ISSUE TITLE
Feature: Move from pascal-case package to change-case package

### ISSUE THREAD

**Issue by lamngockhuong** [tada5hi/typeorm-extension#1071]
### Is your feature request related to a problem? Please describe.

https://www.npmjs.com/package/pascal-case
This package has been deprecated. The author suggested moving to the [change-case](https://www.npmjs.com/package/change-case) package

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by tada5hi** [comment]
good catch. The only problem with moving to change-case is, that is `esm` only.
However, since we want to support both commonjs and esm modules, this is unfortunately not possible.
