### ISSUE TITLE
Bug: context builder is overwriting props passed to it, specifically runMigrations

### ISSUE THREAD

**Issue by talkl** [tada5hi/typeorm-extension#1177]
### Versions
- Node: v18.17.0
- OS: Mac OS 14.6.1 (23G93)

### Reproduction

In both

[createDatabase](https://github.com/tada5hi/typeorm-extension/blob/develop/src/database/create.ts)
[dropDatabase](https://github.com/tada5hi/typeorm-extension/blob/develop/src/database/drop.ts)

context.migrationsRun

is overwritten to false even if passed as true
this is caused by the [context builder](https://github.com/tada5hi/typeorm-extension/blob/develop/src/database/utils/context.ts#L18)

### Steps to reproduce

createDatabase and pass the following options:
`const testRDBConfig: DataSourceOptions = {
  type: 'postgres',
  username: 'postgres',
  password: '...',
  database: 'test',
  logging: false,
  entities: [`${__dirname}/entities/*.ts`],
  namingStrategy: new SnakeNamingStrategy(),
  migrationsRun: true,
  migrations: [`${__dirname}/migration/**/*.ts`]
};

console.log({beforeMutation: testRDBConfig});

await dropDatabase({ options: testRDBConfig, ifExist: true });
await createDatabase({ options: testRDBConfig, ifNotExist: false, synchronize: false });

console.log({afterMutation: testRDBConfig});

`

### What is Expected?

afterMutation config is the same as beforeMutation

### What is actually happening?

afterMutation config has migrationsRun: false instead of false

**Comment by tada5hi** [comment]
Sorry, for the late response.
You can simply set the `synchronize` option to **true**, when calling the `createDatabase` fn.
This will either apply the defined migraitons if defined. Otherwise it will use the lazy synchronization feature provided by typeorm.

**Comment by tada5hi** [comment]
Reference:
- Driver example: https://github.com/tada5hi/typeorm-extension/blob/ab8765957b70d6d779216ded66e27f30c387e7d9/src/database/driver/mysql.ts#L81
- Synchronize fn: https://github.com/tada5hi/typeorm-extension/blob/develop/src/database/utils/schema.ts

**Comment by talkl** [comment]
works, thnx, Object.assign is confusing I guess lol
