### ISSUE TITLE
Only create database without creating table

### ISSUE THREAD

**Issue by rogeriobispo** [Tada5hi/typeorm-extension#12]
Hi, I find great your lib, but I would like to use it only to create db without table. 

but all the time its create the table.

**Comment by geovannimp** [comment]
I have the same problem.

I think the synchronize command should handle this, but its not working.

I made a PR to fix:
https://github.com/Tada5hi/typeorm-extension/pull/13

**Comment by Tada5hi** [comment]
@rogeriobispo glad you like it. And good catch by both of you.
Thanks for the pull request @geovannimp :).
