### ISSUE TITLE
Feature: support for "extra" connection options (with MySQL)

### ISSUE THREAD

**Issue by sturtevant** [tada5hi/typeorm-extension#131]
### Is your feature request related to a problem? Please describe.

TypeORM supports [passing extra connection options](https://typeorm.io/#/connection-options/common-connection-options) to the underlying driver. This appears to be unsupported by typeorm-extension's [simplified view of connection options.](https://github.com/tada5hi/typeorm-extension/blob/master/src/database/driver/mysql.ts). The result is that connection methods such as Unix sockets (see below config) that work fine with TypeORM are unsupported by TypeORM-Extension. This is significant for me because Unix sockets are the primary way to securely to connect to Google Cloud SQL instances from other Google services like Cloud Run ([link](https://cloud.google.com/sql/docs/mysql/connect-run)).

### Describe the solution you'd like

Add support for extra connection options (at least for MySQL) so that the below config will be supported.
See [here](https://github.com/typeorm/typeorm/blob/26581d0264268045496b43f7a0f338eb9f2b70cc/src/connection/BaseConnectionOptions.ts#L111-L116) and [here](https://github.com/typeorm/typeorm/blob/26581d0264268045496b43f7a0f338eb9f2b70cc/src/driver/mysql/MysqlDriver.ts#L966) for the current implementation in TypeORM.

### Describe alternatives you've considered

The only alternative I can think of is to connect via host/port. This is vastly more complicated since the Google-provided mechanism (Unix sockets) makes security simple & transparent.

### Additional context

Here is an example of a TypeORM config that works fine with the core library but fails with TypeORM-Extension:
```
{
  "type": "mysql",
  "extra": {
    "socketPath": "/var/mysqld/mysqld.sock" # for Google it would be: /cloudsql/<project>:<region>:<database>
  },
  "username": "myuser",
  "password": "mypass",
  "database": "mydb"
}
```

**Comment by tada5hi** [comment]
Thx for opening this issue, this is a really good point you noticed. 
Till now, no `extra` driver options have been passed to any driver.
I have changed this in recent commits: 
ad68cd3547082ee531374e942db637a447bdd8a3
9e4ba5b5ca76660dd1188c510be7e74f465f3290
I hope that everything is working as expected.
I will publish the changes today or tomorrow

**Comment by tada5hi** [comment]
@sturtevant can you confirm that verison[ v1.1.0](https://github.com/tada5hi/typeorm-extension/releases/tag/v1.1.0) solves your issue?

**Comment by tada5hi** [comment]
I will close this issue due no response happened.
