### ISSUE TITLE
Feature: Add domain name to mssql connection options

### ISSUE THREAD

**Issue by ppedro1** [tada5hi/typeorm-extension#151]
Hello! This package seems perfect for a use case I am having problems with. The problem is that the package doesn't pass along domain name in the connection options to the database driver, which prevents me from using our domain controlled SQL accounts. 

I suggest adding the domain name parameter to the passed arguments for at least the MSSQL database driver.

**Comment by tada5hi** [comment]
Glad you like it ☺️
Sorry, for the relatively late reply.
I added domain support for mssql support in the commit: af50f7f024acaca8fe86e94fd29a1cc33c0ed0e6
It will be available with the upcoming Version: `v1.2.0`. If there is still a problem, please let me know.
Greetings
Peter
