### ISSUE TITLE
Specify initial database to connect to when using db:create

### ISSUE THREAD

**Issue by romandvoskin-circle** [Tada5hi/typeorm-extension#18]
It seems there's no way to specify the initial database to connect to when running `db:create`, instead the database is assumed to be the same as the `user`. This seems insufficient, there should be a way to specify the initial database either via `ormconfig` or via CLI argument.

Please correct me if I'm wrong.

**Comment by romandvoskin-circle** [comment]
I figured this out. You have to set the `url` field in ormconfig with the connection string and `database` field for the database to create

**Comment by romandvoskin-circle** [comment]
Well, this only seems to work when the user=database. I would still like to  know how to connect with a user to a database and create another database

**Comment by Tada5hi** [comment]
I hope, that i dont't get you wrong, but why do you need an inital database to connect to, if you want to craete the initial database?
In case i missunderstand the problem, can you maybe provide additional informations or a code snippet, so i can reproduce or understand your problem better?

But in general you can just specify the `connection` via CLI argument, to create a specific database.
For example if you have the following connections defined in your `ormconfig.json`.

```typescript
[{
  "name": "default",
  "type": "mysql",
  "host": "localhost",
  "port": 3306,
  "username": "root",
  "password": "start123",
  "database": "test"
}, {
  "name": "second-connection",
  "type": "mysql",
  "host": "localhost",
  "port": 3306,
  "username": "root",
  "password": "start123",
  "database": "test-second"
}]
```
You can create each of the databases by running the following command:
`typeorm-extension db:create --connection default` or `typeorm-extension db:create --connection second-connection`

**Comment by romandvoskin-circle** [comment]
The issue is with the `postgres` usecase. When connecting to `postgres` you have to specify an initial database or when a database name is omitted on the connection, a database with the same name as the user is expected. The only way I was able to get the code to create a database is to use the `url` field for the general connection and the `database` field to indicate the database to create. This only worked because locally I create a database with the same name as the user.  

Ideally, there should be a dedicated field called `new_database` or `create_database` in the `customOptions` to allow the user to connect to one database and create another.

### Reference:
See how [pg-god](https://www.npmjs.com/package/pg-god) which has two database fields
Also here's some info on the Postgres behavior: https://stackoverflow.com/q/44738937/782185

I ended up bypassing this library

```
import {
  createConnection,
  ConnectionOptions,
  ConnectionOptionsReader,
  Connection,
} from 'typeorm'

const ORMCONFIG = 'ormconfig.createdb.js'
const DBNAME = 'someNewDatabase'

// Entry point to self-executing function
;(async () => {
  // Pick the correct config file
  const connectionOptionsReader = new ConnectionOptionsReader({
    root: process.cwd(),
    configName: ORMCONFIG,
  })

  // Get the connection options
  const connectionOptions: ConnectionOptions = await connectionOptionsReader.get(
    'default'
  )
  const conn = await createConnection(connectionOptions)
  // Create database
  await createPostgresDatabase(conn, DBNAME)
  return conn.close()
})()

/***
 * Creates a postgres database
 * @param connection Postgres connection
 * @param database Name of database to create
 */
export async function createPostgresDatabase(
  connection: Connection,
  database: string
) {
  const existQuery: string = `SELECT *
                              FROM pg_database
                              WHERE lower(datname) = lower('${database}');`

  const existResult = await connection.query(existQuery)

  if (Array.isArray(existResult) && existResult.length > 0) {
    console.log(`Database already exists. Database=${database}`)
    return Promise.resolve()
  }

  /**
   * @link https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresQueryRunner.ts#L326
   */
  let createQuery = `CREATE DATABASE "${database}";`

  return await connection.query(createQuery)
}
```

**Comment by Tada5hi** [comment]
Thx for the Info 👍. This is actually a realy good point.

**Comment by Tada5hi** [comment]
Can you confirm, that the following commit would satisfy your requirements?
https://github.com/Tada5hi/typeorm-extension/commit/41d0616b0d730c35f177c8d248a85891ae12931d

You can now specifiy the initial Database via CLI Option `--initialDatabase <name>` or as part of the first argument of `createDatabase` f.e
```typescript
createDatabase({initialDatabase: 'postgres'});
```

**Comment by romandvoskin-circle** [comment]
It works!
