### ISSUE TITLE
Feature: Support TypeORM@0.3.x

### ISSUE THREAD

**Issue by fossamagna** [tada5hi/typeorm-extension#180]
### Is your feature request related to a problem? Please describe.

Hi. Thank you for making a great package.
I would like to use typeorm-extension with TypeORM@0.3.x.
I can not use latest version of typeorm-extension with TypeORM@0.3.x., because of TypeORM@0.3.0 has many changes.

### Describe the solution you'd like

add support TypeORM@0.3.x

**Comment by tada5hi** [comment]
Hey,
your welcome 😀.
Im actually already working on 0.3x support, in a seperate branch:
https://github.com/tada5hi/typeorm-extension/tree/next

**Comment by tada5hi** [comment]
@fossamagna, if you can confirm, that `v2.0.0` is also working for you, i would close the issue.
[https://www.npmjs.com/package/typeorm-extension/v/2.0.0](https://www.npmjs.com/package/typeorm-extension/v/2.0.0)

**Comment by fossamagna** [comment]
@tada5hi Sorry for the delay. `v2.0.0` is working for me. Thank you.

**Comment by tada5hi** [comment]
Glad to hear. Your welcome.

**Comment by tada5hi** [comment]
@fossamagna, the typeorm-extension version [v2.1.0](https://github.com/tada5hi/typeorm-extension/releases/tag/v2.1.0) also provide seeding functionality to a certain extent by now ✌️.
