### ISSUE TITLE
Typescript - dependency, not just devDependency

### ISSUE THREAD

**Issue by peterdanis** [Tada5hi/typeorm-extension#19]
Hi, you are referencing `Typescript` in `utils/index.ts`, please move it from `devDependencies` to `dependencies`.

**Comment by Tada5hi** [comment]
Hi, thx for the hint. Should be fixex with https://github.com/Tada5hi/typeorm-extension/commit/6adc79c816766e6df8d4058c27d8db42e08c8fbb
