### ISSUE TITLE
Bug: Seed command does not work with compiled seeders

### ISSUE THREAD

**Issue by rodrigoscna** [tada5hi/typeorm-extension#219]
### Versions
- Node: 16.14.2
- OS: Ubuntu 20.04
- typeorm: 0.3.6
- typeorm-extension: 2.1.2

### Reproduction
- Setup a TypeScript project with typeorm and typeorm-extension.
- Transpile it using tsc or swc.
- Make sure the dataSource settings are configured to use the compiled files;
```
seeds: ['dist/seeds/**/*.js'],
```
- Run the `seed` command of the CLI

### What is Expected?
The extension should run the seeders as expected.

### What is actually happening?
The extension simply ignores the existence of the seeders. I think it has something to do with the fact that the compiled files do not implement the Seeder interface, since it's not supported in plain JavaScript.

**Comment by tada5hi** [comment]
Hey @rodrigoscna,

sorry for the late response :pensive: .
I think the problem, that you encounter, is that you use the `data-source.ts` file instead of the compiled `data-source.js` file. 
If you are using the cli just specifiy the **dist** location via `--root=<dist location>`. In case that approach,  does not solve your problem, it would be great if you could provide any code or repository. 
Otherwise i could also provide some examples in this repository if you wish.

Greetings
Peter

**Comment by AaronMcCloskey** [comment]
Having the same issue.

It works using explicit definitions. But when running tests via `Jest`.

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From __tests__/user.test.ts.
```

I tried targeting my `dist` folder like so

```
seeds: [path.join(__dirname, '../../dist/src/seeds/**/*{.ts,.js}')],
factories: [path.join(__dirname, '../../dist/src/factories/**/*{.ts,.js}')],
```
Which does run but I get the following error

```
EntityMetadataNotFoundError: No metadata for "User" was found.
```

This is my Seeder
```
export default class UserSeeder implements Seeder {
  public async run(_: DataSource, factoryManager: SeederFactoryManager): Promise<any> {
    await factoryManager.get(User).saveMany(5);
  }
}
```

If I try to target the `.ts` folder for the Seeder it doesn't run at all.

```
seeds: [path.join(__dirname, '../../src/seeds/**/*{.ts,.js}')],
factories: [path.join(__dirname, '../../src/factories/**/*{.ts,.js}')],
```

I'm not running via the CLI, but via `runSeeders`

**Comment by AaronMcCloskey** [comment]
Having the same issue.

It works using explicit definitions.  Like so

```
import UserSeeder from '../seeds/UserSeeder';
import userFactory from '../factories/user.factory';

export const seedDb = async () => {
  return runSeeders(testDs, {
    seeds: [UserSeeder],
    factories: [userFactory],
  });
};
```

But when running tests via Jest. I get the following

`ReferenceError: You are trying to import a file after the Jest environment has been torn down. From __tests__/user.test.ts.`

I tried targeting my dist folder like so

```
seeds: [path.join(__dirname, '../../dist/seeds/**/*.js')],
factories: [path.join(__dirname, '../../dist/factories/**/*.js')],
```
Which does run but I get the following error

EntityMetadataNotFoundError: No metadata for "User" was found.
This is my Seeder

```
export default class UserSeeder implements Seeder {
  public async run(_: DataSource, factoryManager: SeederFactoryManager): Promise<any> {
    await factoryManager.get(User).saveMany(5);
  }
}
```
If I try to target the .ts folder for the Seeder it doesn't run at all.

```
seeds: [path.join(__dirname, '../../src/seeds/**/*.ts')],
factories: [path.join(__dirname, '../../src/factories/**/*.ts')],
```

I'm not running via the CLI, but via `runSeeders`.

**Comment by rodrigoscna** [comment]
> Hey @rodrigoscna,
> 
> sorry for the late response 😔 . I think the problem, that you encounter, is that you use the `data-source.ts` file instead of the compiled `data-source.js` file. If you are using the cli just specifiy the **dist** location via `--root=<dist location>`. In case that approach, does not solve your problem, it would be great if you could provide any code or repository. Otherwise i could also provide some examples in this repository if you wish.
> 
> Greetings Peter

Hey @tada5hi, I'm trying to replicate the issue in a new repository, but everything seems to actually work when I do that.
I'll try to investigate if it has something to do with some of my project's config, or even with the fact that it's a monorepo or something like that.

**Comment by tada5hi** [comment]
@rodrigoscna any news on your attempts ?
@AaronMcCloskey do you have an example git repository or code snippet for me to reproduce?

Should i provide examples in this repository ?

**Comment by tada5hi** [comment]
I will close the issue for now. Please feal free to reopen the issue, when you can provide a public repo 😊
