### ISSUE TITLE
Bug: createDatabase does not throw exception when configuration is wrong

### ISSUE THREAD

**Issue by apperside** [tada5hi/typeorm-extension#243]
### Versions
- Node: 14.9.3
- OS: MacOS 12.4

### Reproduction
Given the following snippet where the database credentials are wrong

```typescript
        try {
          const dbConfig: any = {
            type: 'mysql',
            host: 'localhost',
            port: 3306,
            database: 'mydatabasename',
            username: 'root',
            password: 'mypassword',
          };

          await createDatabase({
            options: dbConfig,
          });

        } catch (err) {
          console.log('error is', err);
        }
      }
```
Will hag forever as no exception is thrown nor a result is returned, it just crashes

<img width="964" alt="Screenshot 2022-06-24 at 14 55 40" src="https://user-images.githubusercontent.com/5955338/175541392-60e7ccdc-cd80-460e-bd5d-0fbc6ef28b59.png">

If I set the correct credentials, it properly creates the database

<details open>
<summary>Additional Details</summary>
</details>

### What is Expected?
An exception is thrown if the connection details are wrong

### What is actually happening?
The process crashes without hitting any catch clause

**Comment by tada5hi** [comment]
Doesn't your terminal output show that an error is thrown ?
