### ISSUE TITLE
Bug: data-source files cannot found via cli:seed command

### ISSUE THREAD

**Issue by hhidev** [tada5hi/typeorm-extension#270]
cli seed command cannot found data-source file in non-default directories. I run command in the following directories

```
backend(root directory)
└db
　└seed
　　└user.seeder.ts
　└data-source.ts

```

I run command with option like this..

```
typeorm-extension seed -r db
typeorm-extension seed -r ./db
```

and cli errors 
`TypeORMError: No connection options were found in any orm configuration files.
`
### Versions
- Node: 16.13.0
- OS: mac os 11.5.2
- typeorm: 0.3.7
- typeorm-extension: 2.1.7

### Reproduction

<details open>
<summary>Additional Details</summary>
</details>

**Comment by tada5hi** [comment]
The seed file might not be found, because it could not be read.
The library is now throwing an exception from version `v2.1.8` ongoing, if for example a dependency is missing in the data-source file.
