### ISSUE TITLE
Instuctions for faker is absent

### ISSUE THREAD

**Issue by oruj91** [tada5hi/typeorm-extension#294]
Don't know how to use

**Comment by tada5hi** [comment]
I will add a reference to the docs, thank you for the hint.

[https://fakerjs.dev/guide/](https://fakerjs.dev/guide/)

**Comment by tada5hi** [comment]
2c8817b660afc747f1338a224db1a57d8bb73dbf

Reference to faker library added. If the description is not sufficient enoguh, please let me know and reopen this issue.
