### ISSUE TITLE
`useSeederFactory(Entity).make()` returns Promise

### ISSUE THREAD

**Issue by hienngm** [tada5hi/typeorm-extension#298]
I'm writing the factory for the entity with relations and find that `useSeederFactory(Entity).make()` returns Promise. It makes the FactoryCallback become the async function while It requires a normal function.
I think `make()` shouldn't return the Promise. 
Did I miss something? 
![image](https://user-images.githubusercontent.com/112270783/188201890-69af679d-e3a1-4c58-aa9c-5c158cb8f088.png)

**Comment by tada5hi** [comment]
Good catch.
The factory callback function can now be synchronous or asnychronous.

**Comment by tada5hi** [comment]
Fixed in release: v2.1.10
