### ISSUE TITLE
Bug:  Not recognize factories

### ISSUE THREAD

**Issue by Spartaques** [tada5hi/typeorm-extension#313]
I have an error:

![image](https://user-images.githubusercontent.com/29341175/191761114-99eb90b6-da3e-4c02-af3b-59921d113dd0.png)

My code looks like:
![image](https://user-images.githubusercontent.com/29341175/191760966-4ebbd13e-b2da-4d89-bd21-5fbe35e4d9cd.png)
![image](https://user-images.githubusercontent.com/29341175/191761022-70b97279-826c-4845-99eb-1f681bedffcc.png)
![image](https://user-images.githubusercontent.com/29341175/191761161-d0d25e49-ebd1-40d2-a55a-79d259967d1d.png)

Help me please, what i'm doing wrong?

**Comment by tada5hi** [comment]
If you do not use one of the seeder methods (`runSeeder` `runSeeders`) or the cli, you have to import the seeder factory file manually, somewhere in the import chain of your entrypoint.
In your case you could just add the following line to your controller file:

```typescript
import '../../database/factories/user.factory';
```
