### ISSUE TITLE
Feature: Standalone DB check if exists

### ISSUE THREAD

**Issue by Divaaan** [tada5hi/typeorm-extension#344]
### Is your feature request related to a problem? Please describe.

No issue, just a nice to have

### Describe the solution you'd like

Something to check if the DB exists and create if it doesn't but a standalone function. Currently calling the `createDatabase` function where the `ifNotExist` option is true but would be nice to skip calling the create DB if it already exists.

### Describe alternatives you've considered

None

### Additional context

Just something that would be nice.

**Comment by tada5hi** [comment]
@Divaaan so you are thinking of a seperate function like `checkDatabase` to verify if the database is created or not ?
