### ISSUE TITLE
Bug: EntityMetadataNotFoundError: No metadata for "Entity" was found.

### ISSUE THREAD

**Issue by golubvladimir** [tada5hi/typeorm-extension#387]
### Versions
- Node: 18.4
- OS: MacOS 13

### Reproduction
My project - [https://github.com/golubvladimir/pizza-app/tree/backend/add-seeding](https://github.com/golubvladimir/pizza-app/tree/backend/add-seeding)
Seeders and factories - [https://github.com/golubvladimir/pizza-app/tree/backend/add-seeding/backend/src/database](https://github.com/golubvladimir/pizza-app/tree/backend/add-seeding/backend/src/database)

### Steps to reproduce
run command by npm - npm run seed

### What is Expected?
Works fine

### What is actually happening?
EntityMetadataNotFoundError: No metadata for "CategoryEntity" was found.

**Comment by golubvladimir** [comment]
I have found same problem - https://github.com/tada5hi/typeorm-extension/issues/219

I tried same way, but it doesn't work for me.

```
```

**Comment by tada5hi** [comment]
@golubvladimir you are problem is not related to this library :see_no_evil: .
You missed to register your database entities for the DataSource :sweat_smile: 

https://github.com/golubvladimir/pizza-app/blob/backend/add-seeding/backend/data-source.ts

The file should look like this:
```typescript
import { DataSource, DataSourceOptions } from 'typeorm';
import { SeederOptions } from 'typeorm-extension';

console.log(process.cwd())

const options: DataSourceOptions & SeederOptions = {
  type: 'mysql',
  database: 'pizza_db',
  port: 8889,
  host: 'localhost',
  password: 'root',
  username: 'root',
  entities: [
	  'src/categories/entities/*{.js,.ts}',
	  'src/products/entities/*{.js,.ts}',
  ],
  seeds: [`${ process.cwd() }/src/database/seeds/**/*{.js,.ts}`],
  factories: [`${ process.cwd() }/src/database/factories/**/*{.js,.ts}`]
};

export const dataSource = new DataSource(options);
```

`

**Comment by golubvladimir** [comment]
It helped. Thanks.

**Comment by tada5hi** [comment]
Glad it helped. Your welcome 🤗

**Comment by Loque18** [comment]
I'm having the same issue, but I'm registering by entities

```ts
export const dataSourceOptions: DataSourceOptions & SeederOptions = {
	type: 'postgres',
	host: 'localhost',
	port: 5432,
	username: 'postgres',
	password: 'password',
	database: 'db',
	synchronize: true,

	//
	entities: ['dist/**/*.entity{.ts,.js}'],
	migrations: ['dist/db/migrations/*.js'],
	seeds: ['src/db/seeds/**/*{.ts,.js}'],
	// factories: ['db/factories/**/*{.ts,.js}'],
};
```

**Comment by tmoubarak** [comment]
same here!

**Comment by jsunwoo** [comment]
FYI: In my case, I replaced the entity path with one that included ../ and that fixed it

For example, I changed path from
import { UserEntity } from 'src/modules/user/entity/user.entity';

to
import { UserEntity } from '../../src/modules/user/entity/user.entity';
