### ISSUE TITLE
Bug: unsupported ts-node-dev package in CLI command approach

### ISSUE THREAD

**Issue by jzfre** [tada5hi/typeorm-extension#462]
### Versions
- Node: 
- OS: 

### Reproduction

<details open>
<summary>Somehow CLI command approach overwrites "src" -> "dist" in paths set by ENV variable</summary>
</details>

### Steps to reproduce
- Install the project
- Set "TYPEORM_SEEDING_SEEDS" to "src/data/seeds/*.ts"
- Run the CLI with "ts-node-dev"

### What is Expected?
It should work

### What is actually happening?
Seeder files are not found

**Comment by tada5hi** [comment]
@jzfre yes, this is the default behavior. The library tries to resolve the `outDir` in the tsconfig.json to allow execution in transpiled state as well as with ts-node.
