### ISSUE TITLE
Bug: Impossible to execute seeds in order

### ISSUE THREAD

**Issue by myself7890** [tada5hi/typeorm-extension#555]
### Versions
- Node: 18.16.0
- OS: Ubuntu 20.04.5

### Reproduction

<details open>
<summary>I named my seeds with 0_country.seeder.ts, 1_client.seeder.ts, etc. to have an order in which I want to launch them, but the CLI command "seed" still don't do it in order, or if it does they are launched asynchronously even with the "parallelExecution" option to false.</summary>
</details>

### Steps to reproduce

- Add "parallelExecution" option and put it to false
- Name seeders with a number at the beginning to have them in order
- Launch CLI command seed

### What is Expected?
I would expect my seeds to be launched in order so that the relationships populate correctly.

### What is actually happening?
The relationships doesn't populate correctly since the seed doesn't launch in order.

**Comment by myself7890** [comment]
`export const configOrm: DataSourceOptions & SeederOptions = {
  type: 'postgres',
  host: process.env.DB_HOST,
  port: parseInt(process.env.DB_PORT),
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: [__dirname + '/**/*.entity{.ts,.js}'],
  synchronize: false,
  migrationsRun: false,
  migrations: [__dirname + '/database/migrations/*{.ts,.js}'],
  seeds: [__dirname + '/database/seeds/**/*{.ts,.js}'],
  factories: [__dirname + '/database/factories/**/*{.ts,.js}'],
  parallelExecution: false,
};`

**Comment by myself7890** [comment]
![image](https://user-images.githubusercontent.com/16654482/235314048-95c9a569-a296-4bdb-9355-743ffe990e9c.png)

**Comment by myself7890** [comment]
UPDATE: They launch in the inverted order....

**Comment by rodrigo1991** [comment]
@myself7890  it's a problem with glob, it started like 1 week for me, same problem, glob is giving files in inverse order now 

`const files = globSync('src/database/seeds/**/*.ts', {
      debug: true,
    });`
so files are: 
03-C.seeder.ts
02-B.seeder.ts
01-A.seeder.ts

**Comment by tada5hi** [comment]
@myself7890 @rodrigo1991 i think the problem should be solved by the following pull request https://github.com/tada5hi/typeorm-extension/pull/546.
I will try to publish a release today.

**Comment by rodrigo1991** [comment]
@tada5hi great, I would appreciate it a lot

**Comment by tada5hi** [comment]
should be resolved with v2.8.0
https://github.com/tada5hi/typeorm-extension/releases/tag/v2.8.0

**Comment by rodrigo1991** [comment]
@tada5hi thanks! is fixed now

**Comment by myself7890** [comment]
Oh, thanks a lot !

**Comment by tada5hi** [comment]
your welcome :relaxed: :v:
