### ISSUE TITLE
Feature: set locale for faker instance

### ISSUE THREAD

**Issue by j0nas** [tada5hi/typeorm-extension#605]
### Is your feature request related to a problem? Please describe.

Hi! Thank you for this wonderful library. It's been working well, and I even have a "Show and tell" feature I'll be posting later. 

With the new v8 version of Faker that we just upgraded to, it is no longer possible to set locale using `faker.locale = ""`, and instead it is handled via imports using `import {faker} from '@faker-js/faker/locale/nb_NO';` or `import { fakerDE as faker } from '@faker-js/faker'`. However, that option is not available when I don't control which instance this library imports. Are there any solutions to this, or do I have to use my own Faker instance? What is the benefit of using the faker instance provided in the seeder factory callback? 

### Describe the solution you'd like

Maybe a third parameter to the seeder factory? Or drop faker from the library altogether and leave it to the users? 

### Describe alternatives you've considered

Importing my own faker instance as per description above.

**Comment by j0nas** [comment]
That is fantastic! Thank you for the impressively swift reply and the planned implementation in v3. Keep up the great work! ❤️

**Comment by tada5hi** [comment]
@j0nas can you check out `v3.0.0-alpha.6`?
You should be able to set the locale in a seeder with:

```typescript
export default class UserSeeder implements Seeder {
    public async run(
        dataSource: DataSource,
        factoryManager: SeederFactoryManager
    ): Promise<any> {
         // ...
        factoryManager.setLocale('de');
        // ...
    }

```

**Comment by j0nas** [comment]
Hey, sorry for the slow reply, I finally got around to upgrading to v3. However, I don't see any `setLocale` method on `SeederFactoryManager

 Did this feature not make the release? 

![image](https://github.com/tada5hi/typeorm-extension/assets/6001131/b614cbd2-24ee-4e6e-b012-0c8e6d9e63bb)


```typescript
import {DataSource} from 'typeorm';
import {Seeder, SeederFactoryManager} from 'typeorm-extension';

export default class CreateUsers implements Seeder {
  public async run(
    dataSource: DataSource,
    factoryManager: SeederFactoryManager,
  ): Promise<void> {
    process.stdout.write('seeding users\n');
    factoryManager.setLocale('nb_NO');
```

**Comment by tada5hi** [comment]
> Hey, sorry for the slow reply, I finally got around to upgrading to v3. However, I don't see any `setLocale` method on `SeederFactoryManager`.
> 
> Did this feature not make the release?
> 
> ![image](https://user-images.githubusercontent.com/6001131/256857131-b614cbd2-24ee-4e6e-b012-0c8e6d9e63bb.png)
> 
> ```ts
> import {DataSource} from 'typeorm';
> import {Seeder, SeederFactoryManager} from 'typeorm-extension';
> 
> export default class CreateUsers implements Seeder {
>   public async run(
>     dataSource: DataSource,
>     factoryManager: SeederFactoryManager,
>   ): Promise<void> {
>     process.stdout.write('seeding users\n');
>     factoryManager.setLocale('nb_NO');
> ```

@j0nas sorry. The `setLocale` method exists on the SeederFactory instance not the SeederFactoryManager instance.

```typescript
import {DataSource} from 'typeorm';
import {Seeder, SeederFactoryManager} from 'typeorm-extension';

export default class CreateUsers implements Seeder {
  public async run(
    dataSource: DataSource,
    factoryManager: SeederFactoryManager,
  ): Promise<void> {
    const userFactory = factoryManager.get(UserEntity);
    userFactory.setLocale('nb_NO');
}
```

**Comment by j0nas** [comment]
@tada5hi  Thank you! 

I'm experiencing an issue with this approach.

I created a getter so that I would always fetch factories with the correct locale set:
```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const getFactory = <T extends Record<string, any>>(
  factoryManager: SeederFactoryManager,
  entity: ObjectType<T>,
): ReturnType<typeof factoryManager.get<T>> => {
  const factory = factoryManager.get(entity);
  factory.setLocale('nb_NO');
  return factory;
};
```

However, it seems like `setLocale` is [the pre-v8 way](https://fakerjs.dev/guide/upgrading.html#breaking-changes) of setting locale. Having migrated my seeds to use this `getFactory(...)`-approach, my seeds now fail:
```
n [Error]: The locale data for 'internet.free_email' are missing in this locale. 
  Please contribute the missing data to the project or use a locale/Faker instanc
e that has these data.    
```
.. or ..
```
n [Error]: The locale data for 'word.noun' are missing in this locale.
  Please contribute the missing data to the project or use a locale/Faker instance that has these data.
```

Maybe setting locale with `.setLocale` doesn't automaticlly set fallbacks? Seems like `faker.localeFallback()` is a separate method. In either case, both of these methods are deprecated in v8. 

(Would it be possible to allow passing in a custom Faker instance? That would decouple this library from `faker` slightly more. 🙂)

**Comment by j0nas** [comment]
@tada5hi Any input here? 😄

**Comment by bondiano** [comment]
I've faced with the same issue using `setSeederFactory`. @tada5hi, Any ideas how to pass faker locale programmatically?

**Comment by j0nas** [comment]
@tada5hi New week, new ping 😄

**Comment by j0nas** [comment]
@tada5hi New week again, new ping. Any thoughts on my post above?

**Comment by j0nas** [comment]
@tada5hi One last attempt at a ping here. 🙂

**Comment by tada5hi** [comment]
@j0nas sorry for the very late reply 😔. i honestly thought i had replied. The problem is that not all locales map all functionalities. Therefore a fallback or multiple locales must be specified.

```typescript
import {DataSource} from 'typeorm';
import {Seeder, SeederFactoryManager} from 'typeorm-extension';

export default class CreateUsers implements Seeder {
  public async run(
    dataSource: DataSource,
    factoryManager: SeederFactoryManager,
  ): Promise<void> {
    const userFactory = factoryManager.get(UserEntity);
    userFactory.setLocale(['nb_NO', 'de_De']);
}
```

**Comment by j0nas** [comment]
I still believe you should consider a "setup" step where the user could pass their own `faker` instance. I think that would let you decouple your library from faker a bit more, and you would need to do less maintenance with regards to changes in faker; just accept a faker instance and call whatever methods you need on it. This would mitigate the locale issue, and likely many others too. What is your thoughts on such an approach?

**Comment by bondiano** [comment]
Any update here? 
I's blocker to update for me. I'm using `useSeederFactory` and seems no way to set locale for them.

**Comment by j0nas** [comment]
@tada5hi
