### ISSUE TITLE
Bug: impossible to run only one seeder

### ISSUE THREAD

**Issue by andkom** [tada5hi/typeorm-extension#631]
### Versions
- Node: 16.13
- OS: OSX
- Lib: 2.8.1

### Steps to reproduce

`src/database/seeds` directory contents:

- a.seeder.ts
- b.seeder.ts
- c.seeder.ts
- my.seeder.ts

`data-source.ts` contents:

```typescript
import { DataSource, DataSourceOptions } from 'typeorm';
import { SeederOptions } from 'typeorm-extension';

const options: DataSourceOptions & SeederOptions = {
    ...
    seeds: ['src/database/seeds/**/*.ts'],
};

export const dataSource = new DataSource(options);
```

Command:

```bash
ts-node ./node_modules/typeorm-extension/dist/cli/index.js -d data-source.ts --seed MySeeder seed
```

### What is Expected?

Only specified seed is executed.

### What is actually happening?

Other seeds being executed before the specified seed.

**Comment by tada5hi** [comment]
@j0nas can you check out `v3.0.0-alpha.9` and verify if the problem persists?
