### ISSUE TITLE
Bug: cannot drop the currently open database

### ISSUE THREAD

**Issue by benjiewheeler** [tada5hi/typeorm-extension#636]
### Versions
- Node: 18.17.0
- NPM: 9.6.7
- Yarn: 1.22.19
- OS: Linux 5.15 Zorin OS 16.2 (based on Ubuntu 20.04)
- typeorm-extension: 2.8.1 (also same issue on 3.0.0-alpha.9)

### Reproduction

<details open>
<summary>Additional Details</summary>

This is used withing a NestJS project, where the relevant database definitions, schemas, seeding, etc... are defined in their own library

these are my relevant **package.json** scripts

```jsonc
{
	// ...
	"typeorm:cli": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli",
	"typeorm-extension:cli": "ts-node -r tsconfig-paths/register ./node_modules/typeorm-extension/bin/cli.cjs -d libs/database/src/seeding/datasource.ts --initialDatabase dummydb",
	"db:create": "npm run typeorm-extension:cli db:create",
	"db:drop": "npm run typeorm-extension:cli db:drop",
	"db:seed": "npm run typeorm-extension:cli seed",
	// ...
}
```
</details>

### Steps to reproduce
example **data-source.ts**
```ts
export const typeOrmDataSourceoptions: DataSourceOptions = {
    type: "postgres",

    host: "127.0.0.1",
    port: 5432,
    username: "admin",
    password: "dummypass",
    database: "dummydb",

    entities: [
      // entities ...
    ],

    synchronize: false,
    logging: true,
    useUTC: true,

    migrations: [__dirname + "/../migrations/*.{js,ts}"],
};
```
run the command
```sh
npm run db:drop
```

### What is Expected?

The selected database to be dropped with no error

### What is actually happening?
The command fails with this error
```
WARN  Failed to drop database.

ERROR  cannot drop the currently open database

 at Parser.parseErrorMessage (node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:369:69)
 at Parser.handlePacket (node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:188:21)
 at Parser.parse (node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:103:30)
 at Socket.<anonymous> (node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/index.ts:7:48)
 at Socket.emit (node:events:513:28)
 at Socket.emit (node:domain:489:12)
 at addChunk (node:internal/streams/readable:315:12)
 at readableAddChunk (node:internal/streams/readable:289:9)
 at Socket.Readable.push (node:internal/streams/readable:228:10)
 at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Proposed solution

The `postgres` database is always present by default in postgres, before connecting, change the `initialDatabase` to `postgres` and from there drop the desired database in `context.database` in here

https://github.com/tada5hi/typeorm-extension/blob/0d9bec3b0af2ba36d233bdee493c4543e9e80eb5/src/database/driver/postgres.ts#L114

I have tested this and it worked.

```diff
-    const connection = await createSimplePostgresConnection(driver, options, context);
+    const connection = await createSimplePostgresConnection(driver, options, { ...context, initialDatabase: "postgres" });
```

**Comment by tada5hi** [comment]
Shouldn't you also be able to specify the `postgres` database as initial database via cli? The problem I see in setting the postgres database as the default initial database is that the user (admin in your case) may not have permissions to connect to it.

**Comment by benjiewheeler** [comment]
I didn't take that into account, you have a good point, after trying with `--initialDatabase postgres` everything seems to work perfectly.

This doesn't need fixing, I'm closing this issue
