### ISSUE TITLE
Bug: Unable to resolve TypeORM decorators (suspect workspace issue)

### ISSUE THREAD

**Issue by snebjorn** [tada5hi/typeorm-extension#655]
### Versions
- Node: v20.2.0
- NPM: 9.6.6
- OS: Windows 11
- ts-node: 10.9.1
- typescript: 5.1.6
- typeorm-extension: 3.0.1
- typeorm: 0.3.17

### Reproduction

I'm using a normal typeorm datasource, it haven't been modified to use any typeorm-extension features yet

Running the below NPM script
```
// package.json scripts
"seed": "ts-node ../node_modules/typeorm-extension/bin/cli.cjs seed:run -d src/db/dataSource.ts",
```
Note the path is `../node_modules`

yields:
```
ℹ DataSource Directory: path\to\src\db
ℹ DataSource Name: dataSource.ts
typeorm-extension seed:run

@Entity()
 ~~~~~~~~
error TS1240: Unable to resolve signature of property decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'Object'.
```
The decorator is
```ts
@Entity()
export class MyEntity { ... }
```

### Steps to reproduce

1. Setup NPM workspace
2. Make a data-source.ts
3. Run one of the typeorm-extension scripts like the seed script: npm run ts-node ../node_modules/typeorm-extension/bin/cli.cjs seed:run -d src/db/dataSource.ts

### What is Expected?

It shouldn't fail to compile.

### What is actually happening?

It's failing to compile. I suspect it has something to do with it being run in a NPM workspace so the path to `../node_modules` is different and that screws up stuff

**Comment by snebjorn** [comment]
Think I figured out what is causing the issue. I happens when entities are imported via a barrel like so:

```ts
// entities/index.ts
export * from "./User"
export * from "./Post"
export * from "./Category"
export * from "./Photo"

// db/data-source.ts
import * as entities from '../entities';

export const AppDataSourceOptions: DataSourceOptions = {
    // ...
    entities: entities,
};
```

**Comment by snebjorn** [comment]
FOUND IT!

The issue is that the when running

**Comment by tada5hi** [comment]
Glad you found the problem ☺️!

**Comment by snebjorn** [comment]
> Sorry, that I didn't reply sooner

No worries :)
