### ISSUE TITLE
Feature: Rollback seeders

### ISSUE THREAD

**Issue by Loque18** [tada5hi/typeorm-extension#659]
Hello !! 
first, I want to thank you for this amazing library, it has definitively help me so much.

It would be great if there was a way to rollback the seeders, because sometimes the database is changing (specially when the structure of it isn't clear), so having a way to rollback the seeder would be very helpful.

it could be executed with a command similar to this 
```sh
npm run seed:revert
 ```

 and it would delete all the entities added to the database added with the seeders.

**Comment by tada5hi** [comment]
I imagine this feature to be quite tricky, as we would have to track which table entries were created using transactions when running the seeder and would have to identify and delete them later. Would you like to make a surcharge, as you have imagined @Loque18 ?

**Comment by netojose** [comment]
Revert migrations, ok. But revert seeders... I guess this is very hard to achieve. How to keep a track about all records inserted? And when removing, how to unmake foreign keys, and how to reset the auto increment database values?

I can't find a way to make this possible, or even useful.

**Comment by tada5hi** [comment]
Totally agree!
I will therefore close the issue for now
