### ISSUE TITLE
Bug: Duplicate shebang lines in v3.1.0

### ISSUE THREAD

**Issue by MartinDybdahlM** [tada5hi/typeorm-extension#737]
### Versions
- Node: 18.16.0
- OS: W11 WSL2 - Ubuntu 22.04.3 LTS

### Reproduction

<details open>
<summary>Additional Details</summary>
When updating to typeorm-extension 3.1.0 and using the CLI commands from `node_modules/typeorm-extension/bin/cli.cjs`, i get the exception:

```
node_modules/typeorm-extension/bin/cli.cjs:2
#!/usr/bin/env node
^

SyntaxError: Invalid or unexpected token
```

I can see in the cli.cjs file that the shebang line is duplicated. The beginning of the file looks like this:
```
#!/usr/bin/env node
#!/usr/bin/env node
'use strict';

require('reflect-metadata');
...
```

</details>

### Steps to reproduce
- install typeorm-extension v3.1.0
- run a cli command like `ts-node --project ./tsconfig.json ../node_modules/typeorm-extension/bin/cli.cjs seed:run -d <PATH TO DATASOURCE>`

### What is Expected?
The command will execute successfully

### What is actually happening?
An exception is thrown because the shebang characters (#!) is only allowed on the first line.

**Comment by tada5hi** [comment]
good catch, thanks!
fixed in `v3.1.1`
