### ISSUE TITLE
Bug: TypeError: ctx.constructor is not a constructor

### ISSUE THREAD

**Issue by muralitharan805** [tada5hi/typeorm-extension#749]
### Versions
- Node: 18.18.2
- OS: ubuntu

### What is actually happening?

this is my datasource for seeds

const options: DataSourceOptions & SeederOptions = {
    type: 'postgres',
    host: process.env.DB_HOST,
    port: +process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB,
    migrations: ['src/database/migration/tenant-information/*.ts'],
    migrationsTableName: 'migration',
    entities: ['src/tenant/**/*.entity.ts'],
    logging: true,
    synchronize: false,
    logger: new TypeormCustomeLog(),
    seeds: ['src/database/seeds/tenant-information/*.ts']
}
export const dataSource = new DataSource(options).initialize();

my package json script 
    "seed:run": "npm run build && ts-node ./node_modules/typeorm-extension/bin/cli.cjs seed:run -d src/shared/typeorm/TenantInformationDbMigration.ts",

*when run the script i get this error, my seeds not complete*

npm run seed:run

> vms@0.0.1 seed:run
> npm run build && ts-node ./node_modules/typeorm-extension/bin/cli.cjs seed:run -d src/shared/typeorm/TenantInformationDbMigration.ts

> vms@0.0.1 build
> nest build

ℹ DataSource Directory: /**/**/src/shared/typeorm 5:39:59 PM
ℹ DataSource Name: TenantInformationDbMigration.ts 5:39:59 PM
typeorm-extension seed:run

Populate the database with an initial data set or generated data by a factory.

Options:
  -h, --help               Show help                                   [boolean]
      --preserveFilePaths  This option indicates if file paths should be
                           preserved.                 [boolean] [default: false]
  -r, --root               Root directory of the project.
                         [default: "/**/**"]
      --tsconfig, --tc     Name (or relative path incl. name) of the tsconfig
                           file.                      [default: "tsconfig.json"]
  -d, --dataSource         Name (or relative path incl. name) of the data-source
                           file.                        [default: "data-source"]
  -n, --name               Name (or relative path incl. name) of the seeder.
  -v, --version            Show version number                         [boolean]

TypeError: ctx.constructor is not a constructor
    at new SeederEntity (/**/**/node_modules/typeorm-extension/src/seeder/entity.ts:54:29)
    at map (/**/**/node_modules/typeorm-extension/src/seeder/executor.ts:195:28)
    at Array.map (<anonymous>)
    at SeederExecutor.buildEntities (/**/**/node_modules/typeorm-extension/src/seeder/executor.ts:178:32)
    at SeederExecutor.execute (/**/**/node_modules/typeorm-extension/src/seeder/executor.ts:46:32)
    at async Object.handler (/**/**/node_modules/typeorm-extension/bin/cli.cjs:264:9)

**Comment by CodeXiD** [comment]
In the newly created seeder you just need to write `export default class` instead of `export class`

**Comment by muralitharan805** [comment]
> In the newly created seeder you just need to write `export default class` instead of `export class`

thank you, tried with 'export default' its worked, however i created seeder file with cli, i used to seed:create as typeorm extension suggested way, cli does not add 'export default' in classes while create seed file

    "seed:create": "ts-node ./node_modules/typeorm-extension/bin/cli.cjs seed:create --name=src/database/seeds/tenant-information/$npm_config_file_name",

**Comment by tada5hi** [comment]
@muralitharan805 good catch, thanks. I will fix that.
