### ISSUE TITLE
Bug: Undefined in DataSource variables

### ISSUE THREAD

**Issue by JMR-Mejia** [tada5hi/typeorm-extension#803]
### Versions
- Node: 18.17.1
- OS: Linux 22.04 LTS

### Reproduction

When the seed:run command is used as indicated in the documentation, it does not take the values ​​found in the data source file, leaving all fields as undefined or default

### Steps to reproduce

Just creating a basic data source file
```
import { DataSource, DataSourceOptions } from 'typeorm';
import { config } from 'dotenv';
import { SeederOptions } from 'typeorm-extension';
import InitSeeder from './src/database/seeds/test/init.seeder';

config();

const options: DataSourceOptions & SeederOptions = {
  type: 'postgres',
  host: 'process.env.POSTGRES_HOST',
  port: 5432,
  database: 'trippster',
  username: 'postgres',
  password: 'password',
  seeds: [InitSeeder],
  ssl:
    process.env.NODE_ENV === 'production'
      ? { rejectUnauthorized: false }
      : false,
  synchronize: true,
  logging: true,
  entities: ['src/**/*.entity.ts'],
  migrations: ['src/database/migrations/*.ts'],
};

console.log(options);

const dataSource = new DataSource(options);

console.log(dataSource);

export { dataSource };
```
and using the command

```
"seed:run": "ts-node ./node_modules/typeorm-extension/bin/cli.cjs seed:run"
```

### What is Expected?

It is expected to connect to the db and load the seeds, but it gives me the following error

```
Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
```
as if I had not provided the data

Debugging I found the error is in the part of the merge where the options supplied by the data source and the ones read by the env

![image](https://github.com/tada5hi/typeorm-extension/assets/51868559/54d805a9-e7bf-4c43-8290-de0adbbc5b99)
![image](https://github.com/tada5hi/typeorm-extension/assets/51868559/4762f4d0-b9ac-49a8-8e8a-620356e57e8f)

attached images to show that the data arrives up to that point and then returns the datasource in the cli as if it were undefined

**Comment by tada5hi** [comment]
mhh, that can only happen if you set env variables. But in general one should consider that when merging options, non-undefined values have priority.
