### ISSUE TITLE
Bug: useSeederFactory(Entity).saveMany(n) saves entities slowly

### ISSUE THREAD

**Issue by arthurgubaidullin** [tada5hi/typeorm-extension#929]
Within the for loop, await is used, which makes the entire loop sequential.

### Versions
- Node: v20.11.0
- OS: linux, mac

### Steps to reproduce

```ts
await useSeederFactory(Entity).saveMany(1000);
```

Problem in [file](https://github.com/tada5hi/typeorm-extension/blob/048408c7942a90982eef491860fc390500294192/src/seeder/factory/module.ts#L83).

### What is Expected?

I expect the entities to persist in parallel.

### What is actually happening?

Entities are stored sequentially.

### Solution

```
    public async saveMany(
        amount: number,
        params?: Partial<O>,
        options?: SaveOptions,
    ) : Promise<O[]> {
        const items : Promise<O>[] = [];
        for (let i = 0; i < amount; i++) {
            const item = this.save(params, options);
            items.push(item);
        }

        return Promise.all(items);
    }
```

### P.S.

Unfortunately, I can't make the changes myself as the tests are constantly flicking.

**Comment by tada5hi** [comment]
good catch!
